[package]
name = "scx-rs-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
libc = "0.2.137"
libbpf-rs = "0.24.1"
scx_utils = "1.0.5"
ctrlc = "3.4.5"

[build-dependencies]
scx_utils = "1.0.5"
